/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package project-0.1.0.0 */
#define VERSION_project "0.1.0.0"
#define MIN_VERSION_project(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)

/* package base-4.9.1.0 */
#define VERSION_base "4.9.1.0"
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  9 || \
  (major1) == 4 && (major2) == 9 && (minor) <= 1)

/* package base64-bytestring-1.0.0.1 */
#define VERSION_base64_bytestring "1.0.0.1"
#define MIN_VERSION_base64_bytestring(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 0)

/* package binary-0.8.3.0 */
#define VERSION_binary "0.8.3.0"
#define MIN_VERSION_binary(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 3)

/* package bytestring-0.10.8.1 */
#define VERSION_bytestring "0.10.8.1"
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 8)

/* package containers-0.5.7.1 */
#define VERSION_containers "0.5.7.1"
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 7)

/* package cryptonite-0.23 */
#define VERSION_cryptonite "0.23"
#define MIN_VERSION_cryptonite(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  23 || \
  (major1) == 0 && (major2) == 23 && (minor) <= 0)

/* package memory-0.14.11 */
#define VERSION_memory "0.14.11"
#define MIN_VERSION_memory(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  14 || \
  (major1) == 0 && (major2) == 14 && (minor) <= 11)

/* package mtl-2.2.1 */
#define VERSION_mtl "2.2.1"
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 1)

/* package network-2.6.3.2 */
#define VERSION_network "2.6.3.2"
#define MIN_VERSION_network(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  6 || \
  (major1) == 2 && (major2) == 6 && (minor) <= 3)

/* package network-transport-0.4.4.0 */
#define VERSION_network_transport "0.4.4.0"
#define MIN_VERSION_network_transport(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 4)

/* package network-transport-tcp-0.5.1 */
#define VERSION_network_transport_tcp "0.5.1"
#define MIN_VERSION_network_transport_tcp(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 1)

/* package pretty-1.1.3.3 */
#define VERSION_pretty "1.1.3.3"
#define MIN_VERSION_pretty(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 3)

/* package text-1.2.2.2 */
#define VERSION_text "1.2.2.2"
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 2)

/* package time-1.6.0.1 */
#define VERSION_time "1.6.0.1"
#define MIN_VERSION_time(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  6 || \
  (major1) == 1 && (major2) == 6 && (minor) <= 0)

/* package utf8-string-1.0.1.1 */
#define VERSION_utf8_string "1.0.1.1"
#define MIN_VERSION_utf8_string(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 1)

/* tool cpphs-1.20.8 */
#define TOOL_VERSION_cpphs "1.20.8"
#define MIN_TOOL_VERSION_cpphs(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  20 || \
  (major1) == 1 && (major2) == 20 && (minor) <= 8)

/* tool gcc-8.2.1 */
#define TOOL_VERSION_gcc "8.2.1"
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  2 || \
  (major1) == 8 && (major2) == 2 && (minor) <= 1)

/* tool ghc-8.0.2 */
#define TOOL_VERSION_ghc "8.0.2"
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  0 || \
  (major1) == 8 && (major2) == 0 && (minor) <= 2)

/* tool ghc-pkg-8.0.2 */
#define TOOL_VERSION_ghc_pkg "8.0.2"
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  0 || \
  (major1) == 8 && (major2) == 0 && (minor) <= 2)

/* tool haddock-2.17.3 */
#define TOOL_VERSION_haddock "2.17.3"
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  17 || \
  (major1) == 2 && (major2) == 17 && (minor) <= 3)

/* tool happy-1.19.8 */
#define TOOL_VERSION_happy "1.19.8"
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  19 || \
  (major1) == 1 && (major2) == 19 && (minor) <= 8)

/* tool hpc-0.67 */
#define TOOL_VERSION_hpc "0.67"
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  67 || \
  (major1) == 0 && (major2) == 67 && (minor) <= 0)

/* tool hsc2hs-0.68.1 */
#define TOOL_VERSION_hsc2hs "0.68.1"
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 1)

/* tool hscolour-1.24 */
#define TOOL_VERSION_hscolour "1.24"
#define MIN_TOOL_VERSION_hscolour(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  24 || \
  (major1) == 1 && (major2) == 24 && (minor) <= 0)

/* tool pkg-config-1.5.4 */
#define TOOL_VERSION_pkg_config "1.5.4"
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  5 || \
  (major1) == 1 && (major2) == 5 && (minor) <= 4)

/* tool strip-2.31 */
#define TOOL_VERSION_strip "2.31"
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  31 || \
  (major1) == 2 && (major2) == 31 && (minor) <= 0)

#define CURRENT_COMPONENT_ID "project-0.1.0.0-HU7FLxM2XVg3AvwUH9JLOk"

#define CURRENT_PACKAGE_KEY "project-0.1.0.0-HU7FLxM2XVg3AvwUH9JLOk"


#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
